/**
 * Sync Plans — fetches all active Stripe products and generates src/plans.ts
 * Run: pnpm sync:plans (from packages/auth)
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { config } from "dotenv";
import Stripe from "stripe";

const PACKAGE_ROOT = resolve(import.meta.dirname, "..");

config({ path: resolve(process.cwd(), "apps/portfolio/.env") });

// ─── Validate env ──────────────────────────────────────────────────
if (!process.env.STRIPE_SECRET_KEY?.trim()) {
  console.log(
    `\n  \x1b[41m\x1b[1m\x1b[37m ✗ MISSING \x1b[0m  \x1b[31mSTRIPE_SECRET_KEY\x1b[0m is not set in \x1b[33m.env.local\x1b[0m\n`
  );
  process.exit(1);
}

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

// ─── ANSI helpers ──────────────────────────────────────────────────
const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  cyan: "\x1b[36m",
  gray: "\x1b[90m",
  bgGreen: "\x1b[42m",
  bgRed: "\x1b[41m",
  white: "\x1b[37m",
  red: "\x1b[31m",
};

// ─── Helpers ───────────────────────────────────────────────────────
function toCamelCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .trim()
    .split(/\s+/)
    .map((word, i) =>
      i === 0
        ? word.toLowerCase()
        : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
    )
    .join("");
}

type PlanEntry = { key: string; name: string; priceId: string };

// ─── Main ──────────────────────────────────────────────────────────
async function main() {
  console.log();

  let products: Stripe.Product[];
  try {
    const result = await stripe.products.list({
      active: true,
      expand: ["data.default_price"],
      limit: 100,
    });
    products = result.data;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.log(
      `  ${c.bgRed}${c.bold}${c.white} ✗ STRIPE API ${c.reset}  ${c.red}${msg}${c.reset}\n`
    );
    process.exit(1);
  }

  if (products.length === 0) {
    console.log(`  ${c.yellow}No active products found in Stripe.${c.reset}\n`);
    process.exit(0);
  }

  const plans: PlanEntry[] = [];
  const oneTimeProducts: PlanEntry[] = [];

  for (const product of products) {
    const price =
      typeof product.default_price === "object" && product.default_price
        ? product.default_price
        : null;

    if (!price?.id) {
      console.log(
        `  ${c.yellow}⚠${c.reset} ${c.dim}Skipping "${product.name}" — no default price${c.reset}`
      );
      continue;
    }

    const entry: PlanEntry = {
      key: toCamelCase(product.name),
      name: product.name,
      priceId: price.id,
    };

    if (price.recurring) {
      plans.push(entry);
    } else {
      oneTimeProducts.push(entry);
    }
  }

  // Sort plans by unit_amount (cheapest first) for natural hierarchy
  const sortByPrice = (a: PlanEntry, b: PlanEntry) => {
    const priceA = products.find(
      (p) =>
        typeof p.default_price === "object" && p.default_price?.id === a.priceId
    )?.default_price;
    const priceB = products.find(
      (p) =>
        typeof p.default_price === "object" && p.default_price?.id === b.priceId
    )?.default_price;
    const amountA =
      typeof priceA === "object" && priceA ? (priceA.unit_amount ?? 0) : 0;
    const amountB =
      typeof priceB === "object" && priceB ? (priceB.unit_amount ?? 0) : 0;
    return amountA - amountB;
  };

  plans.sort(sortByPrice);
  oneTimeProducts.sort(sortByPrice);

  // ─── Generate file ──────────────────────────────────────────────
  const formatEntries = (entries: PlanEntry[]) =>
    entries
      .map((e) => `  ${e.key}: { name: "${e.name}", priceId: "${e.priceId}" },`)
      .join("\n");

  const content = `// Auto-generated by: pnpm sync:plans
// Do not edit manually — re-run the script after changing Stripe products.

export const plans = {
${formatEntries(plans)}
} as const satisfies Record<string, { name: string; priceId: string }>;

export const oneTimeProducts = {
${formatEntries(oneTimeProducts)}
} as const satisfies Record<string, { name: string; priceId: string }>;

export type PlanKey = keyof typeof plans;
export type ProductKey = keyof typeof oneTimeProducts;
`;

  const outPath = resolve(PACKAGE_ROOT, "src/plans.ts");
  writeFileSync(outPath, content, "utf-8");

  // ─── Output ─────────────────────────────────────────────────────
  console.log(
    `  ${c.bgGreen}${c.bold}${c.white} ✓ SYNCED ${c.reset}  ${c.green}packages/auth/src/plans.ts${c.reset}\n`
  );

  if (plans.length > 0) {
    console.log(`  ${c.bold}${c.cyan}Subscription Plans${c.reset}`);
    for (const p of plans) {
      console.log(
        `  ${c.green}│${c.reset} ${p.key} → ${c.dim}${p.name}${c.reset} ${c.gray}(${p.priceId})${c.reset}`
      );
    }
    console.log();
  }

  if (oneTimeProducts.length > 0) {
    console.log(`  ${c.bold}${c.cyan}One-Time Products${c.reset}`);
    for (const p of oneTimeProducts) {
      console.log(
        `  ${c.green}│${c.reset} ${p.key} → ${c.dim}${p.name}${c.reset} ${c.gray}(${p.priceId})${c.reset}`
      );
    }
    console.log();
  }
}

main();
