// Auto-generated by: pnpm sync:plans
// Do not edit manually — re-run the script after changing Stripe products.

export const plans = {} as const satisfies Record<
  string,
  { name: string; priceId: string }
>;

export const oneTimeProducts = {
  motion: { name: "Motion", priceId: "price_1TSmk8G7Gvayjjm6R54evlxU" },
} as const satisfies Record<string, { name: string; priceId: string }>;

export type PlanKey = keyof typeof plans;
export type ProductKey = keyof typeof oneTimeProducts;
