import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

import "./globals.css";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} mx-auto max-w-2xl bg-background py-16 text-foreground max-md:px-4`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
