/**
 * Comment-preserving surgical merge of .pages.yml via the yaml Document API.
 *
 * Contract: existence-checked appends ONLY. Existing entries/fields are never
 * modified, reordered, or deleted — user edits always win. New leaf fields are
 * written in flow style (`- { name: heading, type: string }`) matching the
 * hand-authored house style.
 */

import {
  Document,
  isMap,
  isScalar,
  isSeq,
  parseDocument,
  YAMLMap,
  YAMLSeq,
} from "yaml";

import type { ContentEntry, FieldDef } from "../types.js";

export type PagesDoc = Document.Parsed | Document;

export function loadPagesYml(source: string | null): PagesDoc {
  if (source !== null && source.trim() !== "") {
    return parseDocument(source);
  }
  const doc = new Document({});
  doc.commentBefore =
    " Generated by cms-bridge. Field paths mirror the JSON keys in src/data/.";
  return doc;
}

export function savePagesYml(doc: PagesDoc): string {
  // Default flow padding: house style is `- { name: heading, type: string }`.
  return doc.toString({ lineWidth: 100 });
}

// ---------------------------------------------------------------------------
// Node builders
// ---------------------------------------------------------------------------

/** Build a field node; leaf fields get flow style, object fields block style. */
function fieldNode(doc: PagesDoc, field: FieldDef): YAMLMap {
  const { fields, ...rest } = field;
  const node = doc.createNode(rest) as YAMLMap;
  if (!fields?.length) {
    node.flow = true;
    // Nested option maps stay flow too.
    for (const pair of node.items) {
      if (isMap(pair.value)) (pair.value as YAMLMap).flow = true;
      if (isSeq(pair.value)) (pair.value as YAMLSeq).flow = true;
    }
    return node;
  }
  const fieldsSeq = new YAMLSeq();
  for (const child of fields) fieldsSeq.add(fieldNode(doc, child));
  node.set(doc.createNode("fields"), fieldsSeq);
  return node;
}

function entryNode(doc: PagesDoc, entry: ContentEntry): YAMLMap {
  const { fields, ...rest } = entry;
  const node = doc.createNode(rest) as YAMLMap;
  if (fields?.length) {
    const fieldsSeq = new YAMLSeq();
    for (const field of fields) fieldsSeq.add(fieldNode(doc, field));
    node.set(doc.createNode("fields"), fieldsSeq);
  }
  return node;
}

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

const nameOf = (node: unknown): string | undefined => {
  if (!isMap(node)) return undefined;
  const value = (node as YAMLMap).get("name", true);
  return isScalar(value) && typeof value.value === "string"
    ? value.value
    : undefined;
};

/** Find a content entry map by name, descending into groups. */
export function findEntry(doc: PagesDoc, name: string): YAMLMap | undefined {
  const content = doc.getIn(["content"], true);
  if (!isSeq(content)) return undefined;
  const search = (seq: YAMLSeq): YAMLMap | undefined => {
    for (const item of seq.items) {
      if (!isMap(item)) continue;
      const map = item as YAMLMap;
      if (nameOf(map) === name) return map;
      if (map.get("type") === "group") {
        const items = map.get("items", true);
        if (isSeq(items)) {
          const found = search(items as YAMLSeq);
          if (found) return found;
        }
      }
    }
    return undefined;
  };
  return search(content as YAMLSeq);
}

function ensureContentSeq(doc: PagesDoc): YAMLSeq {
  let content = doc.getIn(["content"], true);
  if (!isSeq(content)) {
    content = new YAMLSeq();
    doc.setIn(["content"], content);
  }
  return content as YAMLSeq;
}

// ---------------------------------------------------------------------------
// Merge operations (all existence-checked)
// ---------------------------------------------------------------------------

export function ensureMedia(doc: PagesDoc): boolean {
  if (doc.hasIn(["media"])) return false;
  doc.setIn(["media"], doc.createNode({ input: "public/media", output: "/media" }));
  return true;
}

export function ensureLinkComponent(doc: PagesDoc): boolean {
  if (doc.hasIn(["components", "link"])) return false;
  const link = doc.createNode({ type: "object" }) as YAMLMap;
  const fieldsSeq = new YAMLSeq();
  fieldsSeq.add(
    fieldNode(doc, { name: "label", label: "Button label", type: "string" })
  );
  fieldsSeq.add(
    fieldNode(doc, {
      name: "link",
      label: "Button link",
      type: "string",
      options: { type: "url" },
    })
  );
  link.set(doc.createNode("fields"), fieldsSeq);
  doc.setIn(["components", "link"], link);
  return true;
}

export function ensurePreviewPath(
  doc: PagesDoc,
  entryName: string,
  route: string
): boolean {
  if (doc.hasIn(["settings", "preview", "paths", entryName])) return false;
  doc.setIn(["settings", "preview", "paths", entryName], route);
  return true;
}

export function ensurePreviewGlobal(doc: PagesDoc, entryName: string): boolean {
  const global = doc.getIn(["settings", "preview", "global"], true);
  if (isSeq(global)) {
    const existing = (global as YAMLSeq).items.some(
      (item) => isScalar(item) && item.value === entryName
    );
    if (existing) return false;
    (global as YAMLSeq).add(doc.createNode(entryName));
    return true;
  }
  const seq = new YAMLSeq();
  seq.flow = true;
  seq.add(doc.createNode(entryName));
  doc.setIn(["settings", "preview", "global"], seq);
  return true;
}

/**
 * Merge missing field definitions into an entry's fields (recursive by name
 * for object fields). Existing fields are never touched.
 */
export function mergeFields(
  doc: PagesDoc,
  entryMap: YAMLMap,
  defs: FieldDef[],
  options?: { seoFirst?: boolean }
): number {
  let fieldsSeq = entryMap.get("fields", true) as unknown;
  if (!isSeq(fieldsSeq)) {
    fieldsSeq = new YAMLSeq();
    (entryMap as YAMLMap<unknown, unknown>).set("fields", fieldsSeq);
  }
  const seq = fieldsSeq as YAMLSeq;
  let added = 0;

  for (const def of defs) {
    const existing = seq.items.find((item) => nameOf(item) === def.name);
    if (!existing) {
      const node = fieldNode(doc, def);
      if (def.name === "seo" && options?.seoFirst) {
        seq.items.unshift(node);
      } else {
        seq.add(node);
      }
      added++;
      continue;
    }
    // Recurse into existing object fields to append missing nested fields.
    if (def.fields?.length && isMap(existing)) {
      const map = existing as YAMLMap;
      const nested = map.get("fields", true);
      if (isSeq(nested)) {
        added += mergeFields(doc, map, def.fields);
      }
    }
  }
  return added;
}

/**
 * Ensure a content entry exists, merging missing fields when it does.
 * Placement for new entries: `site` at index 0; page entries inside a `pages`
 * group when present, else appended at top level.
 */
export function ensureEntry(
  doc: PagesDoc,
  entry: ContentEntry,
  options?: { first?: boolean }
): { created: boolean; fieldsAdded: number } {
  const existing = findEntry(doc, entry.name);
  if (existing) {
    const fieldsAdded = entry.fields?.length
      ? mergeFields(doc, existing, entry.fields, { seoFirst: true })
      : 0;
    return { created: false, fieldsAdded };
  }

  const content = ensureContentSeq(doc);
  const node = entryNode(doc, entry);

  if (options?.first) {
    content.items.unshift(node);
    return { created: true, fieldsAdded: entry.fields?.length ?? 0 };
  }

  // Prefer an existing `pages` group for page entries.
  const pagesGroup = (content.items.find(
    (item) => isMap(item) && nameOf(item) === "pages" && (item as YAMLMap).get("type") === "group"
  ) ?? undefined) as YAMLMap | undefined;
  if (pagesGroup && entry.type === "file" && entry.name !== "site") {
    const items = pagesGroup.get("items", true);
    if (isSeq(items)) {
      (items as YAMLSeq).add(node);
      return { created: true, fieldsAdded: entry.fields?.length ?? 0 };
    }
  }

  content.add(node);
  return { created: true, fieldsAdded: entry.fields?.length ?? 0 };
}

/** Ensure a group exists at top level; returns its items seq. */
export function ensureGroup(doc: PagesDoc, name: string, label?: string): YAMLSeq {
  const content = ensureContentSeq(doc);
  const existing = content.items.find(
    (item) =>
      isMap(item) &&
      nameOf(item) === name &&
      (item as YAMLMap).get("type") === "group"
  ) as YAMLMap | undefined;
  if (existing) {
    let items = existing.get("items", true) as unknown;
    if (!isSeq(items)) {
      items = new YAMLSeq();
      (existing as YAMLMap<unknown, unknown>).set("items", items);
    }
    return items as YAMLSeq;
  }
  const group = doc.createNode({
    name,
    ...(label ? { label } : {}),
    type: "group",
  }) as YAMLMap;
  const items = new YAMLSeq();
  group.set(doc.createNode("items"), items);
  content.add(group);
  return items;
}

/**
 * Ensure an entry inside a specific group (used by collections sync). The
 * group is supplied lazily so it's only created when an entry is actually
 * added.
 */
export function ensureEntryInGroup(
  doc: PagesDoc,
  groupItems: YAMLSeq | (() => YAMLSeq),
  entry: ContentEntry
): { created: boolean; fieldsAdded: number } {
  const existing = findEntry(doc, entry.name);
  if (existing) {
    const fieldsAdded = entry.fields?.length
      ? mergeFields(doc, existing, entry.fields)
      : 0;
    return { created: false, fieldsAdded };
  }
  const seq = typeof groupItems === "function" ? groupItems() : groupItems;
  seq.add(entryNode(doc, entry));
  return { created: true, fieldsAdded: entry.fields?.length ?? 0 };
}
