import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ali Reza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header */}
        <header></header>

        {/* About */}
        <section></section>

        {/* Projects */}
        <section></section>

        {/* Blogs */}
        <section></section>

        {/* Testimonial */}
        <section></section>
      </main>
    </>
  );
}
