import type { Metadata } from "next";
import "./globals.css";

import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import { ThemeProvider } from "next-themes";
import ThemeButton from "@/components/ThemeButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="px-4">
        <ThemeProvider attribute="class" disableTransitionOnChange>
          {children}

          <ThemeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
