// ═══════════════════════════════════════════════════════════════
//  PROJECTS — content source for /work and the homepage work grids
// ═══════════════════════════════════════════════════════════════
//
// "client" entries are live sites built for real businesses; "concept"
// entries are demo builds that showcase capabilities. Client screenshots
// are generated by scripts/fetch-client-screenshots.mjs (Playwright,
// self-hosted webp in public/clients/) — re-run it when a client's hero
// changes, the cards pick the new image up on the next deploy.

export interface Project {
  slug: string;
  kind: "client" | "concept";
  name: string;
  category: string;
  description: string;
  url: string;
  image?: { src: string; alt: string };
}

export const PROJECTS: Project[] = [
  // ── Client work (live sites) ───────────────────────────────────
  {
    slug: "hazara-oregon",
    kind: "client",
    name: "Hazara Community of Oregon",
    category: "Nonprofit · Community",
    description:
      "Website with donations, programs, and membership for an Afghan-immigrant community nonprofit.",
    url: "https://www.hazaraoregon.org/",
    image: {
      src: "/clients/hazara-oregon.webp",
      alt: "Hazara Community of Oregon website",
    },
  },
  {
    slug: "empowerher-initiative",
    kind: "client",
    name: "EmpowerHer Initiative",
    category: "Nonprofit · Women's Empowerment",
    description:
      "Advocacy site for a women's empowerment initiative — programs, resources, and ways to get involved.",
    url: "https://www.empowerher-initiative.org/",
    image: {
      src: "/clients/empowerher-initiative.webp",
      alt: "EmpowerHer Initiative website",
    },
  },
  {
    slug: "mohammad-samadi",
    kind: "client",
    name: "Mohammad Samadi",
    category: "Home Services · Remodeling",
    description:
      "Portfolio site for a Florida remodeling & handyman contractor — services and before/after gallery.",
    url: "https://mohammadsamadi.com/",
    image: {
      src: "/clients/mohammad-samadi.webp",
      alt: "Mohammad Samadi website",
    },
  },

  // ── Concept projects (demo builds) ─────────────────────────────
  {
    slug: "meridian-studio",
    kind: "concept",
    name: "Meridian Studio",
    category: "Creative · Brand & Web",
    description: "Brand identity & web platform for a boutique design studio.",
    url: "https://demo-booking-gray.vercel.app/",
    image: { src: "/meridian.webp", alt: "Meridian Studio project" },
  },
  {
    slug: "clearwater-revenue-partners",
    kind: "concept",
    name: "Clearwater Revenue Partners",
    category: "Hospitality · Revenue Strategy",
    description:
      "Strategy platform for hotel revenue management & partnerships.",
    url: "https://clearwater-revenue-partners.vercel.app/",
    image: {
      src: "/clearwater.webp",
      alt: "Clearwater Revenue Partners project",
    },
  },
  {
    slug: "pinnacle-tax-group",
    kind: "concept",
    name: "Pinnacle Tax Group",
    category: "Finance · Tax Services",
    description:
      "Professional website for a tax preparation & consulting firm.",
    url: "https://tax-preparer.vercel.app/",
    image: { src: "/pinnacle.webp", alt: "Pinnacle Tax Group project" },
  },
  {
    slug: "aether-properties",
    kind: "concept",
    name: "Aether Properties",
    category: "Real Estate · Property Listings",
    description:
      "Architectural real estate platform for luxury property listings.",
    url: "https://real-state-rho-sand.vercel.app/",
    image: { src: "/aether.webp", alt: "Aether Properties project" },
  },
];

export const CLIENT_PROJECTS = PROJECTS.filter((p) => p.kind === "client");
export const CONCEPT_PROJECTS = PROJECTS.filter((p) => p.kind === "concept");
