export { AgencyClient, type AgencyClientOptions } from "./client.js";
export { AgencyError, type AgencyErrorCode, type Result } from "./error.js";
export {
  AdminResource,
  AdminEmailLogsResource,
  AdminEnvsResource,
  AdminKeysResource,
  AdminUsersResource,
} from "./resources/admin.js";
export {
  AdminMarketingResource,
  MarketingResource,
} from "./resources/marketing.js";
export type {
  SendEmailRequest,
  SendEmailResponse,
  SendContactRequest,
  EmailLogEntry,
  EmailHtmlResponse,
  ListEmailsParams,
  ListEmailsResponse,
  NamingStrategy,
  PresignUploadRequest,
  PresignUploadResponse,
  UploadOptions,
  UploadResult,
  DeleteUploadRequest,
  ListObjectsParams,
  StorageObject,
  ListObjectsResponse,
  AgencyUser,
  MeResponse,
  ApiKeyType,
  AdminApiKey,
  AdminApiKeyWithOwner,
  CreateApiKeyRequest,
  CreatedApiKey,
  MigrateLegacyEntry,
  MigrateLegacyResponse,
  CreateApiUserRequest,
  CreateApiUserResponse,
  UpdateApiUserRequest,
  LookupUserResponse,
  EmailStats,
  AdminEmailLogEntry,
  AdminEmailLogsParams,
  AdminEmailLogsResponse,
  EnvFileMeta,
  EnvFileMetaWithOwner,
  CreateEnvFileRequest,
  UpdateEnvFileRequest,
  SesHealth,
  AdminHealthResult,
  MarketingActRequest,
  MarketingSendResponse,
  MarketingSubscribeRequest,
  MarketingSubscribeResponse,
  MarketingTestResponse,
  MarketingTransitionResponse,
} from "./types.js";
